<?php
    /* @var $block \Magento\Sales\Block\Order\History\Container */
  ?>
<div class="block block-order-details-view">
    <div class="block-content">
        <div class="box box-order-comment">
            <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Delivery Date') ?></span></strong>
            <div class="box-content">
    <?= $block->escapeHtml($block->getOrder()->getDeliveryDate()) ?>
    </div>
        </div>
    </div>
</div>