
<?php if ($block->displayNoscriptNotice()): ?>
    <noscript>
        
        <div class="message global noscript">
            <div class="content">
                <p>
                    <strong><?= /* @escapeNotVerified */ __('JavaScript seems to be disabled in your browser.') ?></strong>
                    <span><?= /* @escapeNotVerified */ __('For the best experience on our site, be sure to turn on Javascript in your browser.') ?></span>
                </p>
            </div>
        </div>
    </noscript>
<?php endif; ?>
<?php if ($block->displayNoLocalStorageNotice()): ?>
    <div class="notice global site local_storage" style="display: none;">
        <div class="content">
            <p>
                <strong><?= /* @escapeNotVerified */ __('Local Storage seems to be disabled in your browser.') ?></strong><br />
                <?= /* @escapeNotVerified */ __('For the best experience on our site, be sure to turn on Local Storage in your browser.') ?>
            </p>
        </div>
    </div>
    <script>
require(['jquery'], function(jQuery){

        // <![CDATA[
        (function($) {
            var test = 'test';
            try {
                localStorage.setItem(test, test);
                localStorage.removeItem(test);
            } catch(e) {
                $(".notice.global.site.local_storage").show();
            }
        })(jQuery);
        // ]]>

});
</script>
<?php endif; ?>
<?php if ($block->displayDemoNotice()): ?>
    <div class="message global demo">
        <div class="content">
            <h4><?= /* @escapeNotVerified */ __('Limited Period Offer: Flat 25% off + assured 2% NeuCoins on medicines & more offers.') ?><a href="https://www.1mg.com/offers?_nv_ba_clid=13453_0_0_0">Explore</a></h4>
            

        </div>
    </div>
<?php endif; ?>