<?php 
        //create block_identifier static block
        echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_identifier')->toHtml();?>

<?php // echo __('This is test custom block.'); ?>

<div class="message global demo">
        <div class="content">
<h4>     
    
            <a href="#">MEDICINES</a>&nbsp;&emsp;&emsp;&emsp;&emsp;
            <a href="#">LAB TESTS</a>&ensp;&emsp;&emsp;&emsp;&emsp;&emsp;
            <a href="#">CONSULT DOCTORS</a>&emsp;&emsp;&emsp;&emsp;&emsp;
           <a href="#">COVID-19</a>&emsp;&emsp;&emsp;&emsp;&emsp;
           <a href="#">AYURVEDA</a>&emsp;&emsp;&emsp;&emsp;&emsp;
           <a href="#">CARE PLAN</a>

</h4>


        </div>
    </div>