<!DOCTYPE html>
<html>
<body>
	<section class="regular slider">
		<div>
			<img src="<?php echo $block->getBaseUrl() . 'media/slickslider/1.jpg' ?>" />
		</div>
		<div>
		   <img src="<?php echo $block->getBaseUrl() . 'media/slickslider/2.jfif' ?>" />
		</div>
		<div>
			<img src="<?php echo $block->getBaseUrl() . 'media/slickslider/3.jpg' ?>" />
		</div>
		<div>
			<img src="<?php echo $block->getBaseUrl() . 'media/slickslider/4.jpeg' ?>" />
		</div>
		<div>
			<img src="<?php echo $block->getBaseUrl() . 'media/slickslider/5.jpeg' ?>" />
		</div>
		<div>
			<img src="<?php echo $block->getBaseUrl() . 'media/slickslider/6.jpeg' ?>" />
		</div>
	</section>
</body>
</html>